// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

import * as pulumiAzureNative from "@pulumi/azure-native";

export class MyResourceGroup extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'component:index:MyResourceGroup';

    /**
     * Returns true if the given object is an instance of MyResourceGroup.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is MyResourceGroup {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === MyResourceGroup.__pulumiType;
    }

    declare public /*out*/ readonly myResourceGroup: pulumi.Output<pulumiAzureNative.resources.ResourceGroup>;

    /**
     * Create a MyResourceGroup resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: MyResourceGroupArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["myResourceGroup"] = undefined /*out*/;
        } else {
            resourceInputs["myResourceGroup"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(MyResourceGroup.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a MyResourceGroup resource.
 */
export interface MyResourceGroupArgs {
}
